# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Dilip Renkila's blog
email: dilip.renkila@protonmail.com
description: > # this means to ignore newlines until "baseurl:"
  My personal blog which mostly deals with linux, cloud computing and deep learning.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://diliprenkila.github.io" # the base hostname & protocol for your site
github_username:  diliprenkila

# Build settings
markdown: kramdown
